Composition {
	CurrentTime = 3,
	RenderRange = { 0, 180 },
	GlobalRange = { 0, 180 },
	CurrentID = 5331,
	PlaybackUpdateMode = 0,
	Version = "Fusion Studio 16.1.1 build 5",
	SavedOutputs = 2,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
	},
	Tools = {
		Loader1_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "Comp:/images/vignaioli_night_2k.hdr",
					FormatID = "HDRFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			CtrlWZoom = false,
			Inputs = {
				["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "G" }, },
				["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "B" }, },
				["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
				["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "R" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo {
				Pos = { 55.6667, 149.106 },
				Flags = {
					ShowPic = true
				}
			},
		},
		Loader2 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "Comp:/images/dragon.exr",
					FormatID = "OpenEXRFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			CtrlWZoom = false,
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
				["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "R" }, },
				["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "G" }, },
				["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "B" }, },
				["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
				["Clip1.OpenEXRFormat.ZName"] = Input { Value = FuID { "depth.Z" }, },
				["Clip1.OpenEXRFormat.XNormName"] = Input { Value = FuID { "Normal.red" }, },
				["Clip1.OpenEXRFormat.YNormName"] = Input { Value = FuID { "Normal.green" }, },
				["Clip1.OpenEXRFormat.ZNormName"] = Input { Value = FuID { "Normal.blue" }, },
				["Clip1.OpenEXRFormat.XPosName"] = Input { Value = FuID { "Position.red" }, },
				["Clip1.OpenEXRFormat.YPosName"] = Input { Value = FuID { "Position.green" }, },
				["Clip1.OpenEXRFormat.ZPosName"] = Input { Value = FuID { "Position.blue" }, },
			},
			ViewInfo = OperatorInfo {
				Pos = { -167.615, 279.954 },
				Flags = {
					ShowPic = true
				}
			},
		},
		Camera1ZScale = BezierSpline {
			SplineColor = { Red = 254, Green = 43, Blue = 34 },
			NameSet = true,
			KeyFrames = {
				[1] = { 1, Flags = { Linear = true } }
			}
		},
		Camera1YRotation = BezierSpline {
			SplineColor = { Red = 128, Green = 255, Blue = 128 },
			NameSet = true,
			KeyFrames = {
				[1] = { 0, Flags = { Linear = true } }
			}
		},
		Camera1ZRotation = BezierSpline {
			SplineColor = { Red = 128, Green = 128, Blue = 255 },
			NameSet = true,
			KeyFrames = {
				[1] = { 0, Flags = { Linear = true } }
			}
		},
		HS_envReflection1 = MacroOperator {
			CtrlWZoom = false,
			Inputs = ordered() {
				MainInput1 = InstanceInput {
					SourceOp = "PipeRouter4",
					Source = "Input",
					Name = "Env Texture Input",
				},
				Input1 = InstanceInput {
					SourceOp = "_TextureFlip",
					Source = "FlipHoriz",
					ControlGroup = 2,
					Default = 0,
				},
				Input2 = InstanceInput {
					SourceOp = "_TextureFlip",
					Source = "FlipVert",
					ControlGroup = 2,
					Default = 0,
				},
				Input3 = InstanceInput {
					SourceOp = "_ImageScale",
					Source = "LockXY",
					Name = "Tex Scale Lock X/Y",
					Default = 1,
				},
				Input4 = InstanceInput {
					SourceOp = "_ImageScale",
					Source = "XSize",
					Name = "Tex Scale",
					Default = 1,
				},
				Input5 = InstanceInput {
					SourceOp = "_ImageScale",
					Source = "YSize",
					Name = "Tex Y Scale",
					Default = 1,
				},
				Input6 = InstanceInput {
					SourceOp = "cam_Relight_Input",
					Source = "Transform3DOp.Translate.X",
					Expression = "Camera1.Transform3DOp.Translate.X",
					Name = "X",
					MinScale = -100,
					MaxScale = 100,
					Default = 0,
				},
				Input7 = InstanceInput {
					SourceOp = "cam_Relight_Input",
					Source = "Transform3DOp.Translate.Y",
					Expression = "Camera1.Transform3DOp.Translate.Y",
					Name = "Y",
					MinScale = -100,
					MaxScale = 100,
					Default = 0,
				},
				Input8 = InstanceInput {
					SourceOp = "cam_Relight_Input",
					Source = "Transform3DOp.Translate.Z",
					Expression = "Camera1.Transform3DOp.Translate.Z",
					Name = "Z",
					MinScale = -100,
					MaxScale = 100,
					Default = 0,
				},
				Input9 = InstanceInput {
					SourceOp = "_Blur1_2",
					Source = "LockXY",
					Name = "Tex Lock X/Y",
					Default = 1,
				},
				Input10 = InstanceInput {
					SourceOp = "_Blur1_2",
					Source = "XBlurSize",
					Name = "Tex Blur Size",
					Default = 0,
				},
				Input11 = InstanceInput {
					SourceOp = "_Blur1_2",
					Source = "YBlurSize",
					Name = "Tex Y Blur Size",
					Default = 7.9,
				},
				Input12 = InstanceInput {
					SourceOp = "_Dissolve1",
					Source = "ReflectionMode",
					Page = "Controls",
					Default = 0,
				},
				Input13 = InstanceInput {
					SourceOp = "yaw_user",
					Source = "NumberIn1",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input14 = InstanceInput {
					SourceOp = "yaw_user",
					Source = "NumberIn2",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input15 = InstanceInput {
					SourceOp = "yaw_user",
					Source = "NumberIn3",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				MainInput2 = InstanceInput {
					SourceOp = "PipeRouter5",
					Source = "Input",
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "_out_Texture1",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo { Pos = { 277.505, 261.46 } },
			Tools = ordered() {
				ChangeDepth1 = ChangeDepth {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouter4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -1595, 7.75714 } },
				},
				PipeRouter4 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "Loader1_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -1760, 7.75714 } },
				},
				_TextureFlip = Transform {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Edges = Input { Value = 1, },
						Input = Input {
							SourceOp = "_ImageScale",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -1320, 7.75714 } },
				},
				_ImageScale = Scale {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XSize = Input { Value = 0.125, },
						PixelAspect = Input { Value = { 1, 1 }, },
						FilterMethod = Input { Value = 5, },
						Input = Input {
							SourceOp = "ChangeDepth1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -1485, 7.75714 } },
				},
				Crop1_Extend_H_1_1 = Crop {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XSize = Input {
							Value = 768,
							Expression = "Crop1_Extend_H_1_1.Input.OriginalWidth*3",
						},
						YSize = Input {
							Value = 128,
							Expression = "Crop1_Extend_H_1_1.Input.OriginalHeight",
						},
						Input = Input {
							SourceOp = "_TextureFlip",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -1155, 7.75714 } },
				},
				cam_Relight_Input = Camera3D {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input {
							Value = 2.9449999332428,
							Expression = "Camera1.Transform3DOp.Translate.X",
						},
						["Transform3DOp.Translate.Y"] = Input {
							Value = 0.354999989271164,
							Expression = "Camera1.Transform3DOp.Translate.Y",
						},
						["Transform3DOp.Translate.Z"] = Input {
							Value = 1.96000003814697,
							Expression = "Camera1.Transform3DOp.Translate.Z",
						},
						["Transform3DOp.UseTarget"] = Input { Value = 1, },
						PerspNearClip = Input { Value = 0.100000001490116, },
						PerspFarClip = Input { Value = 10000, },
						AovType = Input { Value = 1, },
						AoV = Input { Value = 27.6147462372868, },
						FLength = Input { Value = 50, },
						PlaneOfFocus = Input { Value = 2, },
						["Stereo.Nest"] = Input { Value = 1, },
						["Stereo.Mode"] = Input { Value = FuID { "OffAxis" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 0.9675591010747, },
						ApertureH = Input { Value = 0.7351181638522, },
						ControlVis = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -1265, 205.758 } },
				},
				_Blur1_2 = Blur {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Filter = Input { Value = FuID { "Fast Gaussian" }, },
						XBlurSize = Input { Value = 2, },
						YBlurSize = Input { Value = 7.9, },
						Input = Input {
							SourceOp = "Crop1_Extend_H_1_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -990, 7.75714 } },
				},
				Crop1_reformatToOrigianl_2 = Crop {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XOffset = Input {
							Value = 256,
							Expression = "XSize",
						},
						XSize = Input {
							Value = 256,
							Expression = "Crop1_reformatToOrigianl_2.Input.OriginalWidth/3",
						},
						YSize = Input {
							Value = 128,
							Expression = "Crop1_reformatToOrigianl_2.Input.OriginalHeight",
						},
						Input = Input {
							SourceOp = "_Blur1_2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -825, 7.75714 } },
				},
				CustomTool4 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool4LUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool4LUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool4LUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool4LUTIn4",
							Source = "Value",
						},
						Intermediate1 = Input { Value = "sqrt((r1^2)+(g1^2)+(b1^2))", },
						RedExpression = Input { Value = "r1/i1", },
						GreenExpression = Input { Value = "g1/i1", },
						BlueExpression = Input { Value = "b1/i1", },
						AlphaExpression = Input { Value = "1\n", },
						Image1 = Input {
							SourceOp = "CopyAux1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -825, 337.758 } },
				},
				CustomTool4LUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool4LUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool4LUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool4LUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				Transform2 = Transform {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						UseSizeAndAspect = Input { Value = 0, },
						FlipHoriz = Input { Value = 1, },
						Input = Input {
							SourceOp = "Crop1_reformatToOrigianl_2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -660, 7.75714 } },
				},
				CopyAux1 = Dimension.CopyAux {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Channel = Input { Value = FuID { "Normal" }, },
						OutColorDepth = Input { Value = 2, },
						Input = Input {
							SourceOp = "PipeRouter5",
							Source = "Output",
						},
						Comments = Input { Value = "AUX - Normal To RGB", },
					},
					ViewInfo = OperatorInfo {
						Pos = { -1045, 337.758 },
						Flags = {
							ShowModes = true
						}
					},
				},
				CopyAux1_1 = Dimension.CopyAux {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Channel = Input { Value = FuID { "WorldPos" }, },
						OutColorDepth = Input { Value = 2, },
						Input = Input {
							SourceOp = "PipeRouter5",
							Source = "Output",
						},
						Comments = Input { Value = "AUX World Position To RGB", },
					},
					ViewInfo = OperatorInfo { Pos = { -1045, 436.758 } },
				},
				CustomTool2_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool2_1LUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool2_1LUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool2_1LUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool2_1LUTIn4",
							Source = "Value",
						},
						Setup1 = Input {
							Value = "2.9449999332428",
							Expression = "cam_Relight_Input.Transform3DOp.Translate.X",
						},
						Setup2 = Input {
							Value = "0.35499998927116",
							Expression = "cam_Relight_Input.Transform3DOp.Translate.Y",
						},
						Setup3 = Input {
							Value = "1.960000038147",
							Expression = "cam_Relight_Input.Transform3DOp.Translate.Z",
						},
						Intermediate1 = Input { Value = "r1-s1", },
						Intermediate2 = Input { Value = "g1-s2", },
						Intermediate3 = Input { Value = "b1-s3", },
						Intermediate4 = Input { Value = "sqrt((i1^2)+(i2^2)+(i3^2))", },
						RedExpression = Input { Value = "i1/i4", },
						GreenExpression = Input { Value = "i2/i4", },
						BlueExpression = Input { Value = "i3/i4", },
						AlphaExpression = Input { Value = "1", },
						Image1 = Input {
							SourceOp = "CopyAux1_1",
							Source = "Output",
						},
						Comments = Input { Value = "Normalize Camera Vec", },
					},
					ViewInfo = OperatorInfo { Pos = { -825, 436.758 } },
				},
				CustomTool2_1LUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool2_1LUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool2_1LUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool2_1LUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				PipeRouter5 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "Loader2",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -1265, 337.758 } },
				},
				CustomTool3_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool3_1LUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool3_1LUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool3_1LUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool3_1LUTIn4",
							Source = "Value",
						},
						Intermediate1 = Input { Value = "(r1*r2) + (g1*g2) + (b1*b2)", },
						Intermediate2 = Input { Value = "(r1*r2) + (g1*g2) + (b1*b2)", },
						Intermediate3 = Input { Value = "(r1*r2) + (g1*g2) + (b1*b2)", },
						RedExpression = Input { Value = "i1*2", },
						GreenExpression = Input { Value = "i2*2", },
						BlueExpression = Input { Value = "i3*2", },
						AlphaExpression = Input { Value = "1", },
						NumberControls = Input { Value = 1, },
						Image1 = Input {
							SourceOp = "CustomTool2_1",
							Source = "Output",
						},
						Image2 = Input {
							SourceOp = "CustomTool4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -495, 436.758 } },
				},
				CustomTool3_1LUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool3_1LUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool3_1LUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool3_1LUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				Resize1 = BetterResize {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Width = Input {
							Value = 256,
							Expression = "Resize1.Input.OriginalWidth",
						},
						Height = Input {
							Value = 256,
							Expression = "Width",
						},
						HiQOnly = Input { Expression = "_ImageScale.HiQOnly", },
						PixelAspect = Input { Value = { 1, 1 }, },
						FilterMethod = Input {
							Value = 5,
							Expression = "_ImageScale.FilterMethod",
						},
						Input = Input {
							SourceOp = "Transform2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -495, 7.75714 } },
				},
				PipeRouter1_1 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "CustomTool2_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -715, 469.758 } },
				},
				PipeRouter2_1 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter5",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -1045, 535.758 } },
				},
				CustomTool5 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool5LUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool5LUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool5LUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool5LUTIn4",
							Source = "Value",
						},
						RedExpression = Input { Value = "r1*r2", },
						GreenExpression = Input { Value = "g1*g2", },
						BlueExpression = Input { Value = "b1*b2", },
						Image1 = Input {
							SourceOp = "CustomTool3_1",
							Source = "Output",
						},
						Image2 = Input {
							SourceOp = "CustomTool4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -385, 436.758 } },
				},
				CustomTool5LUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool5LUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool5LUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool5LUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				PipeRouter8 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "Resize1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -385, 7.75714 } },
				},
				_Dissolve1 = Dissolve {
					Transitions = {
						[0] = "DFTDissolve"
					},
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Mix = Input {
							Value = 0,
							Expression = "ReflectionMode",
						},
						Background = Input {
							SourceOp = "CustomTool6",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouter9",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -110, 370.758 } },
					UserControls = ordered() {
						Normal = {
							INP_Integer = false,
							LINKID_DataType = "Number",
							LINKS_Name = "Reflection Mode",
						},
						ReflectionMode = {
							{ MBTNC_AddButton = "Specular" },
							{ MBTNC_AddButton = "Diffuse" },
							INP_MaxAllowed = 1,
							INP_Integer = false,
							INPID_InputControl = "MultiButtonControl",
							MBTNC_ShowBasicButton = false,
							INP_MaxScale = 1,
							INP_Default = 0,
							ICS_ControlPage = "Controls",
							INP_MinScale = 0,
							INP_MinAllowed = 0,
							LINKID_DataType = "Number",
							MBTNC_ShowName = false,
							MBTNC_StretchToFit = false,
							MBTNC_ShowToolTip = false,
							LINKS_Name = "ReflectionMode"
						}
					}
				},
				Crop1 = Crop {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						YOffset = Input {
							Value = 64,
							Expression = "Crop1.Input.OriginalHeight/4",
						},
						XSize = Input {
							Value = 256,
							Expression = "Crop1.Input.OriginalWidth",
						},
						YSize = Input {
							Value = 128,
							Expression = "Crop1.Input.OriginalHeight/2",
						},
						Input = Input {
							SourceOp = "PipeRouter8",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 7.75714 } },
				},
				CustomTool6 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool6LUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool6LUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool6LUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool6LUTIn4",
							Source = "Value",
						},
						Intermediate1 = Input { Value = "r2-r1", },
						Intermediate2 = Input { Value = "g2-g1", },
						Intermediate3 = Input { Value = "b2-b1", },
						Intermediate4 = Input { Value = "sqrt( (i1^2) + (i2^2) + (i3^2))", },
						RedExpression = Input { Value = "i1/i4", },
						GreenExpression = Input { Value = "i2/i4", },
						BlueExpression = Input { Value = "i3/i4", },
						Image1 = Input {
							SourceOp = "CustomTool5",
							Source = "Output",
						},
						Image2 = Input {
							SourceOp = "PipeRouter1_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -275, 469.758 } },
				},
				CustomTool6LUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool6LUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool6LUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool6LUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				PipeRouter2 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter8",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -275, 139.758 } },
				},
				PipeRouter9 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "CustomTool4",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -220, 337.758 } },
				},
				PipeRouter1 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter8",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -275, 73.7572 } },
				},
				CustomTool1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool1LUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool1LUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool1LUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool1LUTIn4",
							Source = "Value",
						},
						RedExpression = Input { Value = "cosr(2*PI*x+PI/2)*sinr(PI*(y))", },
						GreenExpression = Input { Value = "cosr(PI*(1-y))", },
						BlueExpression = Input { Value = "cosr(2*PI*x)*sinr(PI*(y))", },
						Image1 = Input {
							SourceOp = "Crop1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -55, 7.75714 } },
				},
				CustomTool1LUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool1LUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool1LUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool1LUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool8 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool8LUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool8LUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool8LUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool8LUTIn4",
							Source = "Value",
						},
						Intermediate1 = Input { Value = "0.5/pi*acosr(b1)  / sqrt(r1^2  + g1^2)", },
						RedExpression = Input { Value = "0.5 + (r1*i1)", },
						GreenExpression = Input { Value = "0.5 + (g1*i1)", },
						BlueExpression = Input { Value = "0", },
						Image1 = Input {
							SourceOp = "_Dissolve1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 55, 370.758 } },
				},
				CustomTool8LUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool8LUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool8LUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool8LUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				yaw = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						NumberIn1 = Input { Value = -90, },
						LUTIn1 = Input {
							SourceOp = "yawLUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "yawLUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "yawLUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "yawLUTIn4",
							Source = "Value",
						},
						RedExpression = Input { Value = "cos(n2)*r1 + 0 + -sin(n2)*b1", },
						BlueExpression = Input { Value = "sin(n2)*r1 + 0 + cos(n2)*b1", },
						NameforNumber1 = Input { Value = "RotationX", },
						NameforNumber2 = Input { Value = "RotationY", },
						NameforNumber3 = Input { Value = "RotationZ", },
						ShowNumber4 = Input { Value = 0, },
						ShowNumber5 = Input { Value = 0, },
						ShowNumber6 = Input { Value = 0, },
						ShowNumber7 = Input { Value = 0, },
						ShowNumber8 = Input { Value = 0, },
						ShowPoint1 = Input { Value = 0, },
						ShowPoint2 = Input { Value = 0, },
						ShowPoint3 = Input { Value = 0, },
						ShowPoint4 = Input { Value = 0, },
						ShowLUT1 = Input { Value = 0, },
						ShowLUT2 = Input { Value = 0, },
						ShowLUT3 = Input { Value = 0, },
						ShowLUT4 = Input { Value = 0, },
						Image1 = Input {
							SourceOp = "CustomTool1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 110, 7.75714 } },
				},
				yawLUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				yawLUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				yawLUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				yawLUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				CopyAux2 = Dimension.CopyAux {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Mode = Input { Value = 1, },
						Channel = Input { Value = FuID { "Texture" }, },
						Input = Input {
							SourceOp = "CustomTool8",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 220, 370.758 } },
				},
				roll = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						NumberIn1 = Input {
							Value = -90,
							Expression = "yaw.NumberIn1",
						},
						NumberIn2 = Input { Expression = "yaw.NumberIn2", },
						NumberIn3 = Input { Expression = "yaw.NumberIn3", },
						LUTIn1 = Input {
							SourceOp = "rollLUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "rollLUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "rollLUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "rollLUTIn4",
							Source = "Value",
						},
						RedExpression = Input { Value = "cos(n3)*r1 +sin(n3)*g1 + 0 ", },
						GreenExpression = Input { Value = "-sin(n3)*r1 + cos(n3)*g1 +0\n", },
						Image1 = Input {
							SourceOp = "pitch",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 330, 7.75714 } },
				},
				rollLUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				rollLUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				rollLUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				rollLUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				pitch = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						NumberIn1 = Input {
							Value = -90,
							Expression = "yaw.NumberIn1",
						},
						NumberIn2 = Input { Expression = "yaw.NumberIn2", },
						NumberIn3 = Input { Expression = "yaw.NumberIn3", },
						LUTIn1 = Input {
							SourceOp = "pitchLUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "pitchLUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "pitchLUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "pitchLUTIn4",
							Source = "Value",
						},
						GreenExpression = Input { Value = "0 + cos(n1)*g1 + sin(n1)*b1", },
						BlueExpression = Input { Value = "0 + -sin(n1)*g1 + cos(n1)*b1", },
						Image1 = Input {
							SourceOp = "yaw",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 220, 7.75714 } },
				},
				pitchLUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				pitchLUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				pitchLUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				pitchLUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				roll_user = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						NumberIn1 = Input { Expression = "yaw_user.NumberIn1", },
						NumberIn2 = Input { Expression = "yaw_user.NumberIn2", },
						NumberIn3 = Input { Expression = "yaw_user.NumberIn3", },
						LUTIn1 = Input {
							SourceOp = "roll_userLUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "roll_userLUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "roll_userLUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "roll_userLUTIn4",
							Source = "Value",
						},
						RedExpression = Input { Value = "cos(n3)*r1 +sin(n3)*g1 + 0 ", },
						GreenExpression = Input { Value = "-sin(n3)*r1 + cos(n3)*g1 +0\n", },
						Image1 = Input {
							SourceOp = "pitch_user",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 770, 7.75714 } },
				},
				roll_userLUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				roll_userLUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				roll_userLUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				roll_userLUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				yaw_user = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "yaw_userLUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "yaw_userLUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "yaw_userLUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "yaw_userLUTIn4",
							Source = "Value",
						},
						RedExpression = Input { Value = "cos(n2)*r1 + 0 + -sin(n2)*b1", },
						BlueExpression = Input { Value = "sin(n2)*r1 + 0 + cos(n2)*b1", },
						NumberControls = Input { Value = 1, },
						NameforNumber1 = Input { Value = "RotationX", },
						NameforNumber2 = Input { Value = "RotationY", },
						NameforNumber3 = Input { Value = "RotationZ", },
						ShowNumber4 = Input { Value = 0, },
						ShowNumber5 = Input { Value = 0, },
						ShowNumber6 = Input { Value = 0, },
						ShowNumber7 = Input { Value = 0, },
						ShowNumber8 = Input { Value = 0, },
						ShowPoint1 = Input { Value = 0, },
						ShowPoint2 = Input { Value = 0, },
						ShowPoint3 = Input { Value = 0, },
						ShowPoint4 = Input { Value = 0, },
						ShowLUT1 = Input { Value = 0, },
						ShowLUT2 = Input { Value = 0, },
						ShowLUT3 = Input { Value = 0, },
						ShowLUT4 = Input { Value = 0, },
						Image1 = Input {
							SourceOp = "roll",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 550, 7.75714 } },
				},
				yaw_userLUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				yaw_userLUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				yaw_userLUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				yaw_userLUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				pitch_user = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						NumberIn1 = Input { Expression = "yaw_user.NumberIn1", },
						NumberIn2 = Input { Expression = "yaw_user.NumberIn2", },
						NumberIn3 = Input { Expression = "yaw_user.NumberIn3", },
						LUTIn1 = Input {
							SourceOp = "pitch_userLUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "pitch_userLUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "pitch_userLUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "pitch_userLUTIn4",
							Source = "Value",
						},
						GreenExpression = Input { Value = "0 + cos(n1)*g1 + sin(n1)*b1", },
						BlueExpression = Input { Value = "0 + -sin(n1)*g1 + cos(n1)*b1", },
						Image1 = Input {
							SourceOp = "yaw_user",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 660, 7.75714 } },
				},
				pitch_userLUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				pitch_userLUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				pitch_userLUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				pitch_userLUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool2 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool2LUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool2LUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool2LUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool2LUTIn4",
							Source = "Value",
						},
						RedExpression = Input { Value = " (1 + atan2r(b1, r1) / PI )*0.5\n", },
						GreenExpression = Input { Value = "acosr(-g1)/PI", },
						BlueExpression = Input { Value = "0\n", },
						Image1 = Input {
							SourceOp = "roll_user",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 935, 7.75714 } },
				},
				CustomTool2LUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool2LUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool2LUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool2LUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				Texture1 = Texture {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "CustomTool2",
							Source = "Output",
						},
						Texture = Input {
							SourceOp = "PipeRouter3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1100, 7.75714 } },
				},
				CustomTool3 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool3LUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool3LUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool3LUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool3LUTIn4",
							Source = "Value",
						},
						Intermediate1 = Input { Value = "((x - 0) * 2 ) / 1 -1", },
						Intermediate2 = Input { Value = "((y- 0) * 2 ) / 1 -1", },
						RedExpression = Input { Value = "(pi+atan2r(i1,i2))/(2*pi)", },
						GreenExpression = Input { Value = "sqrt((i1^2)+(i2^2))", },
						BlueExpression = Input { Value = "0", },
						Image1 = Input {
							SourceOp = "PipeRouter2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1045, 139.758 } },
				},
				CustomTool3LUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool3LUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool3LUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool3LUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				PipeRouter3 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 1045, 73.7572 } },
				},
				Texture2 = Texture {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "CustomTool3",
							Source = "Output",
						},
						Texture = Input {
							SourceOp = "Texture1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1320, 139.758 } },
				},
				PipeRouter12 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter2_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 1595, 535.758 } },
				},
				PipeRouter10 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "Texture2",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 1540, 139.758 } },
				},
				_out_Texture1 = Texture {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						EffectMask = Input {
							SourceOp = "PipeRouter12",
							Source = "Output",
						},
						MultiplyByMask = Input { Value = 1, },
						Input = Input {
							SourceOp = "CopyAux2",
							Source = "Output",
						},
						Texture = Input {
							SourceOp = "PipeRouter10",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1760, 370.758 } },
				}
			},
		},
		HS_envReflection1_1 = MacroOperator {
			CtrlWZoom = false,
			Inputs = ordered() {
				MainInput1 = InstanceInput {
					SourceOp = "PipeRouter4_1",
					Source = "Input",
					Name = "Env Texture Input",
				},
				Input1 = InstanceInput {
					SourceOp = "_TextureFlip_1",
					Source = "FlipHoriz",
					ControlGroup = 2,
					Default = 0,
				},
				Input2 = InstanceInput {
					SourceOp = "_TextureFlip_1",
					Source = "FlipVert",
					ControlGroup = 2,
					Default = 0,
				},
				Input3 = InstanceInput {
					SourceOp = "_ImageScale_1",
					Source = "LockXY",
					Name = "Tex Scale Lock X/Y",
					Default = 1,
				},
				Input4 = InstanceInput {
					SourceOp = "_ImageScale_1",
					Source = "XSize",
					Name = "Tex Scale",
					Default = 1,
				},
				Input5 = InstanceInput {
					SourceOp = "_ImageScale_1",
					Source = "YSize",
					Name = "Tex Y Scale",
					Default = 1,
				},
				Input6 = InstanceInput {
					SourceOp = "cam_Relight_Input_1",
					Source = "Transform3DOp.Translate.X",
					Expression = "Camera1.Transform3DOp.Translate.X",
					Name = "X",
					MinScale = -100,
					MaxScale = 100,
					Default = 0,
				},
				Input7 = InstanceInput {
					SourceOp = "cam_Relight_Input_1",
					Source = "Transform3DOp.Translate.Y",
					Expression = "Camera1.Transform3DOp.Translate.YCamera2.Transform3DOp.Translate.YCamera1.Transform3DOp.Translate.Y",
					Name = "Y",
					MinScale = -100,
					MaxScale = 100,
					Default = 0,
				},
				Input8 = InstanceInput {
					SourceOp = "cam_Relight_Input_1",
					Source = "Transform3DOp.Translate.Z",
					Expression = "Camera1.Transform3DOp.Translate.Z",
					Name = "Z",
					MinScale = -100,
					MaxScale = 100,
					Default = 0,
				},
				Input9 = InstanceInput {
					SourceOp = "_Blur1_2_1",
					Source = "LockXY",
					Name = "Tex Lock X/Y",
					Default = 1,
				},
				Input10 = InstanceInput {
					SourceOp = "_Blur1_2_1",
					Source = "XBlurSize",
					Name = "Tex Blur Size",
					Default = 0,
				},
				Input11 = InstanceInput {
					SourceOp = "_Blur1_2_1",
					Source = "YBlurSize",
					Name = "Tex Y Blur Size",
					Default = 7.9,
				},
				Input12 = InstanceInput {
					SourceOp = "_Dissolve1_1",
					Source = "ReflectionMode",
					Page = "Controls",
					Default = 0,
				},
				Input13 = InstanceInput {
					SourceOp = "yaw_user_1",
					Source = "NumberIn1",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input14 = InstanceInput {
					SourceOp = "yaw_user_1",
					Source = "NumberIn2",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input15 = InstanceInput {
					SourceOp = "yaw_user_1",
					Source = "NumberIn3",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				MainInput2 = InstanceInput {
					SourceOp = "PipeRouter5_1",
					Source = "Input",
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "_out_Texture1_1",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo { Pos = { 274.165, 379.5 } },
			Tools = ordered() {
				ChangeDepth1_1 = ChangeDepth {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouter4_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -1595, 7.75714 } },
				},
				PipeRouter4_1 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "Loader1_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -1760, 7.75714 } },
				},
				_TextureFlip_1 = Transform {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Edges = Input { Value = 1, },
						Input = Input {
							SourceOp = "_ImageScale_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -1320, 7.75714 } },
				},
				_ImageScale_1 = Scale {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XSize = Input { Value = 0.125, },
						PixelAspect = Input { Value = { 1, 1 }, },
						FilterMethod = Input { Value = 5, },
						Input = Input {
							SourceOp = "ChangeDepth1_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -1485, 7.75714 } },
				},
				Crop1_Extend_H_1_1_1 = Crop {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XSize = Input {
							Value = 768,
							Expression = "Crop1_Extend_H_1_1_1.Input.OriginalWidth*3",
						},
						YSize = Input {
							Value = 128,
							Expression = "Crop1_Extend_H_1_1_1.Input.OriginalHeight",
						},
						Input = Input {
							SourceOp = "_TextureFlip_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -1155, 7.75714 } },
				},
				cam_Relight_Input_1 = Camera3D {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input {
							Value = 2.9449999332428,
							Expression = "Camera1.Transform3DOp.Translate.X",
						},
						["Transform3DOp.Translate.Y"] = Input {
							Value = 0.291100293397903,
							Expression = "Camera1.Transform3DOp.Translate.YCamera2.Transform3DOp.Translate.YCamera1.Transform3DOp.Translate.Y",
						},
						["Transform3DOp.Translate.Z"] = Input {
							Value = 1.96000003814697,
							Expression = "Camera1.Transform3DOp.Translate.Z",
						},
						["Transform3DOp.UseTarget"] = Input { Value = 1, },
						PerspNearClip = Input { Value = 0.100000001490116, },
						PerspFarClip = Input { Value = 10000, },
						AovType = Input { Value = 1, },
						AoV = Input { Value = 27.6147462372868, },
						FLength = Input { Value = 50, },
						PlaneOfFocus = Input { Value = 2, },
						["Stereo.Nest"] = Input { Value = 1, },
						["Stereo.Mode"] = Input { Value = FuID { "OffAxis" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 0.9675591010747, },
						ApertureH = Input { Value = 0.7351181638522, },
						ControlVis = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -1265, 205.758 } },
				},
				_Blur1_2_1 = Blur {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Filter = Input { Value = FuID { "Fast Gaussian" }, },
						XBlurSize = Input { Value = 160, },
						YBlurSize = Input { Value = 7.9, },
						Input = Input {
							SourceOp = "Crop1_Extend_H_1_1_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -990, 7.75714 } },
				},
				Crop1_reformatToOrigianl_2_1 = Crop {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XOffset = Input {
							Value = 256,
							Expression = "XSize",
						},
						XSize = Input {
							Value = 256,
							Expression = "Crop1_reformatToOrigianl_2_1.Input.OriginalWidth/3",
						},
						YSize = Input {
							Value = 128,
							Expression = "Crop1_reformatToOrigianl_2_1.Input.OriginalHeight",
						},
						Input = Input {
							SourceOp = "_Blur1_2_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -825, 7.75714 } },
				},
				CustomTool4_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool4LUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool4LUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool4LUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool4LUTIn4_1",
							Source = "Value",
						},
						Intermediate1 = Input { Value = "sqrt((r1^2)+(g1^2)+(b1^2))", },
						RedExpression = Input { Value = "r1/i1", },
						GreenExpression = Input { Value = "g1/i1", },
						BlueExpression = Input { Value = "b1/i1", },
						AlphaExpression = Input { Value = "1\n", },
						Image1 = Input {
							SourceOp = "CopyAux1_2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -825, 337.758 } },
				},
				CustomTool4LUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool4LUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool4LUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool4LUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				Transform2_1 = Transform {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						UseSizeAndAspect = Input { Value = 0, },
						FlipHoriz = Input { Value = 1, },
						Input = Input {
							SourceOp = "Crop1_reformatToOrigianl_2_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -660, 7.75714 } },
				},
				CopyAux1_2 = Dimension.CopyAux {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Channel = Input { Value = FuID { "Normal" }, },
						OutColorDepth = Input { Value = 2, },
						Input = Input {
							SourceOp = "PipeRouter5_1",
							Source = "Output",
						},
						Comments = Input { Value = "AUX - Normal To RGB", },
					},
					ViewInfo = OperatorInfo {
						Pos = { -1045, 337.758 },
						Flags = {
							ShowModes = true
						}
					},
				},
				CopyAux1_1_1 = Dimension.CopyAux {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Channel = Input { Value = FuID { "WorldPos" }, },
						OutColorDepth = Input { Value = 2, },
						Input = Input {
							SourceOp = "PipeRouter5_1",
							Source = "Output",
						},
						Comments = Input { Value = "AUX World Position To RGB", },
					},
					ViewInfo = OperatorInfo { Pos = { -1045, 436.758 } },
				},
				CustomTool2_1_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool2_1LUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool2_1LUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool2_1LUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool2_1LUTIn4_1",
							Source = "Value",
						},
						Setup1 = Input {
							Value = "2.9449999332428",
							Expression = "cam_Relight_Input_1.Transform3DOp.Translate.X",
						},
						Setup2 = Input { Expression = "cam_Relight_Input_1.Transform3DOp.Translate.Y", },
						Setup3 = Input {
							Value = "1.960000038147",
							Expression = "cam_Relight_Input_1.Transform3DOp.Translate.Z",
						},
						Intermediate1 = Input { Value = "r1-s1", },
						Intermediate2 = Input { Value = "g1-s2", },
						Intermediate3 = Input { Value = "b1-s3", },
						Intermediate4 = Input { Value = "sqrt((i1^2)+(i2^2)+(i3^2))", },
						RedExpression = Input { Value = "i1/i4", },
						GreenExpression = Input { Value = "i2/i4", },
						BlueExpression = Input { Value = "i3/i4", },
						AlphaExpression = Input { Value = "1", },
						Image1 = Input {
							SourceOp = "CopyAux1_1_1",
							Source = "Output",
						},
						Comments = Input { Value = "Normalize Camera Vec", },
					},
					ViewInfo = OperatorInfo { Pos = { -825, 436.758 } },
				},
				CustomTool2_1LUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool2_1LUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool2_1LUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool2_1LUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				PipeRouter5_1 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "Loader2",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -1265, 337.758 } },
				},
				CustomTool3_1_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool3_1LUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool3_1LUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool3_1LUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool3_1LUTIn4_1",
							Source = "Value",
						},
						Intermediate1 = Input { Value = "(r1*r2) + (g1*g2) + (b1*b2)", },
						Intermediate2 = Input { Value = "(r1*r2) + (g1*g2) + (b1*b2)", },
						Intermediate3 = Input { Value = "(r1*r2) + (g1*g2) + (b1*b2)", },
						RedExpression = Input { Value = "i1*2", },
						GreenExpression = Input { Value = "i2*2", },
						BlueExpression = Input { Value = "i3*2", },
						AlphaExpression = Input { Value = "1", },
						NumberControls = Input { Value = 1, },
						Image1 = Input {
							SourceOp = "CustomTool2_1_1",
							Source = "Output",
						},
						Image2 = Input {
							SourceOp = "CustomTool4_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -495, 436.758 } },
				},
				CustomTool3_1LUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool3_1LUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool3_1LUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool3_1LUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				Resize1_1 = BetterResize {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Width = Input {
							Value = 256,
							Expression = "Resize1_1.Input.OriginalWidth",
						},
						Height = Input {
							Value = 256,
							Expression = "Width",
						},
						HiQOnly = Input { Expression = "_ImageScale_1.HiQOnly", },
						PixelAspect = Input { Value = { 1, 1 }, },
						FilterMethod = Input {
							Value = 5,
							Expression = "_ImageScale_1.FilterMethod",
						},
						Input = Input {
							SourceOp = "Transform2_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -495, 7.75714 } },
				},
				PipeRouter1_1_1 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "CustomTool2_1_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -715, 469.758 } },
				},
				PipeRouter2_1_1 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter5_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -1045, 535.758 } },
				},
				CustomTool5_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool5LUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool5LUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool5LUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool5LUTIn4_1",
							Source = "Value",
						},
						RedExpression = Input { Value = "r1*r2", },
						GreenExpression = Input { Value = "g1*g2", },
						BlueExpression = Input { Value = "b1*b2", },
						Image1 = Input {
							SourceOp = "CustomTool3_1_1",
							Source = "Output",
						},
						Image2 = Input {
							SourceOp = "CustomTool4_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -385, 436.758 } },
				},
				CustomTool5LUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool5LUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool5LUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool5LUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				PipeRouter8_1 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "Resize1_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -385, 7.75714 } },
				},
				_Dissolve1_1 = Dissolve {
					Transitions = {
						[0] = "DFTDissolve"
					},
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Mix = Input {
							Value = 0,
							Expression = "ReflectionMode",
						},
						Background = Input {
							SourceOp = "CustomTool6_1",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouter9_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -110, 370.758 } },
					UserControls = ordered() {
						Normal = {
							INP_Integer = false,
							LINKID_DataType = "Number",
							LINKS_Name = "Reflection Mode",
						},
						ReflectionMode = {
							{ MBTNC_AddButton = "Specular" },
							{ MBTNC_AddButton = "Diffuse" },
							INP_MaxAllowed = 1,
							INP_Integer = false,
							INPID_InputControl = "MultiButtonControl",
							MBTNC_ShowBasicButton = false,
							INP_MaxScale = 1,
							INP_Default = 0,
							ICS_ControlPage = "Controls",
							INP_MinScale = 0,
							INP_MinAllowed = 0,
							LINKID_DataType = "Number",
							MBTNC_ShowName = false,
							MBTNC_StretchToFit = false,
							MBTNC_ShowToolTip = false,
							LINKS_Name = "ReflectionMode"
						}
					}
				},
				Crop1_1 = Crop {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						YOffset = Input {
							Value = 64,
							Expression = "Crop1_1.Input.OriginalHeight/4",
						},
						XSize = Input {
							Value = 256,
							Expression = "Crop1_1.Input.OriginalWidth",
						},
						YSize = Input {
							Value = 128,
							Expression = "Crop1_1.Input.OriginalHeight/2",
						},
						Input = Input {
							SourceOp = "PipeRouter8_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 7.75714 } },
				},
				CustomTool6_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool6LUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool6LUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool6LUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool6LUTIn4_1",
							Source = "Value",
						},
						Intermediate1 = Input { Value = "r2-r1", },
						Intermediate2 = Input { Value = "g2-g1", },
						Intermediate3 = Input { Value = "b2-b1", },
						Intermediate4 = Input { Value = "sqrt( (i1^2) + (i2^2) + (i3^2))", },
						RedExpression = Input { Value = "i1/i4", },
						GreenExpression = Input { Value = "i2/i4", },
						BlueExpression = Input { Value = "i3/i4", },
						Image1 = Input {
							SourceOp = "CustomTool5_1",
							Source = "Output",
						},
						Image2 = Input {
							SourceOp = "PipeRouter1_1_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -275, 469.758 } },
				},
				CustomTool6LUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool6LUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool6LUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool6LUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				PipeRouter2_2 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter8_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -275, 139.758 } },
				},
				PipeRouter9_1 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "CustomTool4_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -220, 337.758 } },
				},
				PipeRouter1_2 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter8_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -275, 73.7572 } },
				},
				CustomTool1_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool1LUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool1LUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool1LUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool1LUTIn4_1",
							Source = "Value",
						},
						RedExpression = Input { Value = "cosr(2*PI*x+PI/2)*sinr(PI*(y))", },
						GreenExpression = Input { Value = "cosr(PI*(1-y))", },
						BlueExpression = Input { Value = "cosr(2*PI*x)*sinr(PI*(y))", },
						Image1 = Input {
							SourceOp = "Crop1_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -55, 7.75714 } },
				},
				CustomTool1LUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool1LUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool1LUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool1LUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool8_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool8LUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool8LUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool8LUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool8LUTIn4_1",
							Source = "Value",
						},
						Intermediate1 = Input { Value = "0.5/pi*acosr(b1)  / sqrt(r1^2  + g1^2)", },
						RedExpression = Input { Value = "0.5 + (r1*i1)", },
						GreenExpression = Input { Value = "0.5 + (g1*i1)", },
						BlueExpression = Input { Value = "0", },
						Image1 = Input {
							SourceOp = "_Dissolve1_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 55, 370.758 } },
				},
				CustomTool8LUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool8LUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool8LUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool8LUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				yaw_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						NumberIn1 = Input { Value = -90, },
						LUTIn1 = Input {
							SourceOp = "yawLUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "yawLUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "yawLUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "yawLUTIn4_1",
							Source = "Value",
						},
						RedExpression = Input { Value = "cos(n2)*r1 + 0 + -sin(n2)*b1", },
						BlueExpression = Input { Value = "sin(n2)*r1 + 0 + cos(n2)*b1", },
						NameforNumber1 = Input { Value = "RotationX", },
						NameforNumber2 = Input { Value = "RotationY", },
						NameforNumber3 = Input { Value = "RotationZ", },
						ShowNumber4 = Input { Value = 0, },
						ShowNumber5 = Input { Value = 0, },
						ShowNumber6 = Input { Value = 0, },
						ShowNumber7 = Input { Value = 0, },
						ShowNumber8 = Input { Value = 0, },
						ShowPoint1 = Input { Value = 0, },
						ShowPoint2 = Input { Value = 0, },
						ShowPoint3 = Input { Value = 0, },
						ShowPoint4 = Input { Value = 0, },
						ShowLUT1 = Input { Value = 0, },
						ShowLUT2 = Input { Value = 0, },
						ShowLUT3 = Input { Value = 0, },
						ShowLUT4 = Input { Value = 0, },
						Image1 = Input {
							SourceOp = "CustomTool1_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 110, 7.75714 } },
				},
				yawLUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				yawLUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				yawLUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				yawLUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				CopyAux2_1 = Dimension.CopyAux {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Mode = Input { Value = 1, },
						Channel = Input { Value = FuID { "Texture" }, },
						Input = Input {
							SourceOp = "CustomTool8_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 220, 370.758 } },
				},
				roll_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						NumberIn1 = Input {
							Value = -90,
							Expression = "yaw_1.NumberIn1",
						},
						NumberIn2 = Input { Expression = "yaw_1.NumberIn2", },
						NumberIn3 = Input { Expression = "yaw_1.NumberIn3", },
						LUTIn1 = Input {
							SourceOp = "rollLUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "rollLUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "rollLUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "rollLUTIn4_1",
							Source = "Value",
						},
						RedExpression = Input { Value = "cos(n3)*r1 +sin(n3)*g1 + 0 ", },
						GreenExpression = Input { Value = "-sin(n3)*r1 + cos(n3)*g1 +0\n", },
						Image1 = Input {
							SourceOp = "pitch_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 330, 7.75714 } },
				},
				rollLUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				rollLUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				rollLUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				rollLUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				pitch_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						NumberIn1 = Input {
							Value = -90,
							Expression = "yaw_1.NumberIn1",
						},
						NumberIn2 = Input { Expression = "yaw_1.NumberIn2", },
						NumberIn3 = Input { Expression = "yaw_1.NumberIn3", },
						LUTIn1 = Input {
							SourceOp = "pitchLUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "pitchLUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "pitchLUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "pitchLUTIn4_1",
							Source = "Value",
						},
						GreenExpression = Input { Value = "0 + cos(n1)*g1 + sin(n1)*b1", },
						BlueExpression = Input { Value = "0 + -sin(n1)*g1 + cos(n1)*b1", },
						Image1 = Input {
							SourceOp = "yaw_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 220, 7.75714 } },
				},
				pitchLUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				pitchLUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				pitchLUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				pitchLUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				roll_user_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						NumberIn1 = Input { Expression = "yaw_user_1.NumberIn1", },
						NumberIn2 = Input { Expression = "yaw_user_1.NumberIn2", },
						NumberIn3 = Input { Expression = "yaw_user_1.NumberIn3", },
						LUTIn1 = Input {
							SourceOp = "roll_userLUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "roll_userLUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "roll_userLUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "roll_userLUTIn4_1",
							Source = "Value",
						},
						RedExpression = Input { Value = "cos(n3)*r1 +sin(n3)*g1 + 0 ", },
						GreenExpression = Input { Value = "-sin(n3)*r1 + cos(n3)*g1 +0\n", },
						Image1 = Input {
							SourceOp = "pitch_user_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 770, 7.75714 } },
				},
				roll_userLUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				roll_userLUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				roll_userLUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				roll_userLUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				yaw_user_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "yaw_userLUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "yaw_userLUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "yaw_userLUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "yaw_userLUTIn4_1",
							Source = "Value",
						},
						RedExpression = Input { Value = "cos(n2)*r1 + 0 + -sin(n2)*b1", },
						BlueExpression = Input { Value = "sin(n2)*r1 + 0 + cos(n2)*b1", },
						NumberControls = Input { Value = 1, },
						NameforNumber1 = Input { Value = "RotationX", },
						NameforNumber2 = Input { Value = "RotationY", },
						NameforNumber3 = Input { Value = "RotationZ", },
						ShowNumber4 = Input { Value = 0, },
						ShowNumber5 = Input { Value = 0, },
						ShowNumber6 = Input { Value = 0, },
						ShowNumber7 = Input { Value = 0, },
						ShowNumber8 = Input { Value = 0, },
						ShowPoint1 = Input { Value = 0, },
						ShowPoint2 = Input { Value = 0, },
						ShowPoint3 = Input { Value = 0, },
						ShowPoint4 = Input { Value = 0, },
						ShowLUT1 = Input { Value = 0, },
						ShowLUT2 = Input { Value = 0, },
						ShowLUT3 = Input { Value = 0, },
						ShowLUT4 = Input { Value = 0, },
						Image1 = Input {
							SourceOp = "roll_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 550, 7.75714 } },
				},
				yaw_userLUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				yaw_userLUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				yaw_userLUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				yaw_userLUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				pitch_user_1 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						NumberIn1 = Input { Expression = "yaw_user_1.NumberIn1", },
						NumberIn2 = Input { Expression = "yaw_user_1.NumberIn2", },
						NumberIn3 = Input { Expression = "yaw_user_1.NumberIn3", },
						LUTIn1 = Input {
							SourceOp = "pitch_userLUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "pitch_userLUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "pitch_userLUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "pitch_userLUTIn4_1",
							Source = "Value",
						},
						GreenExpression = Input { Value = "0 + cos(n1)*g1 + sin(n1)*b1", },
						BlueExpression = Input { Value = "0 + -sin(n1)*g1 + cos(n1)*b1", },
						Image1 = Input {
							SourceOp = "yaw_user_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 660, 7.75714 } },
				},
				pitch_userLUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				pitch_userLUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				pitch_userLUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				pitch_userLUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool2_2 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool2LUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool2LUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool2LUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool2LUTIn4_1",
							Source = "Value",
						},
						RedExpression = Input { Value = " (1 + atan2r(b1, r1) / PI )*0.5\n", },
						GreenExpression = Input { Value = "acosr(-g1)/PI", },
						BlueExpression = Input { Value = "0\n", },
						Image1 = Input {
							SourceOp = "roll_user_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 935, 7.75714 } },
				},
				CustomTool2LUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool2LUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool2LUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool2LUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				Texture1_1 = Texture {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "CustomTool2_2",
							Source = "Output",
						},
						Texture = Input {
							SourceOp = "PipeRouter3_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1100, 7.75714 } },
				},
				CustomTool3_2 = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "CustomTool3LUTIn1_1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomTool3LUTIn2_1",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomTool3LUTIn3_1",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomTool3LUTIn4_1",
							Source = "Value",
						},
						Intermediate1 = Input { Value = "((x - 0) * 2 ) / 1 -1", },
						Intermediate2 = Input { Value = "((y- 0) * 2 ) / 1 -1", },
						RedExpression = Input { Value = "(pi+atan2r(i1,i2))/(2*pi)", },
						GreenExpression = Input { Value = "sqrt((i1^2)+(i2^2))", },
						BlueExpression = Input { Value = "0", },
						Image1 = Input {
							SourceOp = "PipeRouter2_2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1045, 139.758 } },
				},
				CustomTool3LUTIn1_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool3LUTIn2_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomTool3LUTIn3_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomTool3LUTIn4_1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				PipeRouter3_1 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter1_2",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 1045, 73.7572 } },
				},
				Texture2_1 = Texture {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "CustomTool3_2",
							Source = "Output",
						},
						Texture = Input {
							SourceOp = "Texture1_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1320, 139.758 } },
				},
				PipeRouter12_1 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter2_1_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 1595, 535.758 } },
				},
				PipeRouter10_1 = PipeRouter {
					CtrlWZoom = false,
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "Texture2_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 1540, 139.758 } },
				},
				_out_Texture1_1 = Texture {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						EffectMask = Input {
							SourceOp = "PipeRouter12_1",
							Source = "Output",
						},
						MultiplyByMask = Input { Value = 1, },
						Input = Input {
							SourceOp = "CopyAux2_1",
							Source = "Output",
						},
						Texture = Input {
							SourceOp = "PipeRouter10_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1760, 370.758 } },
				}
			},
		},
		Note1 = Note {
			CtrlWZoom = false,
			Inputs = {
				Comments = Input { Value = "Environment map is available at  https://hdrihaven.com/ (CC0 License). To know further information about the license, please visit https://hdrihaven.com/p/license.php.", }
			},
			ViewInfo = StickyNoteInfo {
				Pos = { -326.326, 62.9378 },
				Flags = {
					Expanded = true
				},
				Size = { 476.361, 152.735 }
			},
		},
		Merge1 = Merge {
			CtrlWZoom = false,
			Inputs = {
				Background = Input {
					SourceOp = "Renderer3D1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Dissolve1",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 881.24, 281.627 } },
		},
		CamerafromFBXFile = Underlay {
			CtrlWZoom = false,
			NameSet = true,
			Inputs = {
				Comments = Input { Value = "3D camera from FBX file.", }
			},
			ViewInfo = UnderlayInfo {
				Pos = { 275, -148.5 },
				Size = { 531.73, 127.083 }
			},
		},
		Camera1ZOffset = BezierSpline {
			SplineColor = { Red = 254, Green = 207, Blue = 46 },
			NameSet = true,
			KeyFrames = {
				[1] = { 1.96000003814697, Flags = { Linear = true } }
			}
		},
		Renderer3D1 = Renderer3D {
			CtrlWZoom = false,
			CustomData = {
				ToolVersion = 2,
			},
			Inputs = {
				GlobalOut = Input { Value = 180, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				SceneInput = Input {
					SourceOp = "Merge3D2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 660, 82.5 } },
		},
		Camera1XOffset = BezierSpline {
			SplineColor = { Red = 250, Green = 59, Blue = 49 },
			NameSet = true,
			KeyFrames = {
				[1] = { 2.9449999332428, Flags = { Linear = true } }
			}
		},
		Merge3D2 = Merge3D {
			Inputs = {
				SceneInput1 = Input {
					SourceOp = "Shape3D1",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "Merge3D1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 495, 82.5 } },
		},
		PointCloud3D1 = PointCloud3D {
			CtrlWZoom = false,
			ViewInfo = OperatorInfo { Pos = { 134.264, -72.6861 } },
			Positions = {
				Version = 2,
				[0] = { 0, 0, 0, "Axis2", "" }
			}
		},
		Dissolve1 = Dissolve {
			Transitions = {
				[0] = "DFTDissolve"
			},
			CtrlWZoom = false,
			Inputs = {
				Mix = Input { Value = 0.118, },
				Background = Input {
					SourceOp = "ColorCorrector1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "_out_Texture1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 605, 280.5 } },
		},
		Camera1FocalLengthmm = BezierSpline {
			SplineColor = { Red = 219, Green = 80, Blue = 9 },
			NameSet = true,
			KeyFrames = {
				[1] = { 50 }
			}
		},
		CopyAux3_1 = Dimension.CopyAux {
			CtrlWZoom = false,
			Inputs = {
				Channel = Input { Value = FuID { "WorldPos" }, },
				Input = Input {
					SourceOp = "CopyAux3",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo {
				Pos = { 108.479, 412.5 },
				Flags = {
					ShowPic = true
				}
			},
		},
		ColorCorrector1 = ColorCorrector {
			CtrlWZoom = false,
			Inputs = {
				WheelTintAngle1 = Input { Value = -0.343583520905499, },
				WheelTintLength1 = Input { Value = 0.0273, },
				MasterRGBGain = Input { Value = 0.13, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "_out_Texture1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 439.333, 379.5 } },
		},
		Camera1XScale = BezierSpline {
			SplineColor = { Red = 251, Green = 22, Blue = 119 },
			NameSet = true,
			KeyFrames = {
				[1] = { 1, Flags = { Linear = true } }
			}
		},
		CopyAux3 = Dimension.CopyAux {
			CtrlWZoom = false,
			Inputs = {
				Channel = Input { Value = FuID { "Normal" }, },
				Input = Input {
					SourceOp = "Loader2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo {
				Pos = { 0, 412.5 },
				Flags = {
					ShowPic = true
				}
			},
		},
		Camera1YOffset = BezierSpline {
			SplineColor = { Red = 252, Green = 131, Blue = 47 },
			NameSet = true,
			KeyFrames = {
				[1] = { 0.354999989271164, Flags = { Linear = true } }
			}
		},
		Merge3D1 = Merge3D {
			CtrlWZoom = false,
			Inputs = {
				SceneInput1 = Input {
					SourceOp = "Transform3D1",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "PointCloud3D1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 354.264, -105.686 } },
		},
		Camera1YScale = BezierSpline {
			SplineColor = { Red = 252, Green = 21, Blue = 37 },
			NameSet = true,
			KeyFrames = {
				[1] = { 1, Flags = { Linear = true } }
			}
		},
		Camera1 = Camera3D {
			CtrlWZoom = false,
			Inputs = {
				["Transform3DOp.Translate.X"] = Input {
					SourceOp = "Camera1XOffset",
					Source = "Value",
				},
				["Transform3DOp.Translate.Y"] = Input {
					SourceOp = "Camera1YOffset",
					Source = "Value",
				},
				["Transform3DOp.Translate.Z"] = Input {
					SourceOp = "Camera1ZOffset",
					Source = "Value",
				},
				["Transform3DOp.Rotate.RotOrder"] = Input { Value = FuID { "ZXY" }, },
				["Transform3DOp.Rotate.X"] = Input {
					SourceOp = "Camera1XRotation",
					Source = "Value",
				},
				["Transform3DOp.Rotate.Y"] = Input {
					SourceOp = "Camera1YRotation",
					Source = "Value",
				},
				["Transform3DOp.Rotate.Z"] = Input {
					SourceOp = "Camera1ZRotation",
					Source = "Value",
				},
				["Transform3DOp.Scale.X"] = Input {
					SourceOp = "Camera1XScale",
					Source = "Value",
				},
				["Transform3DOp.Scale.Y"] = Input {
					SourceOp = "Camera1YScale",
					Source = "Value",
				},
				["Transform3DOp.Scale.Z"] = Input {
					SourceOp = "Camera1ZScale",
					Source = "Value",
				},
				["Transform3DOp.UseTarget"] = Input { Value = 1, },
				PerspNearClip = Input { Value = 0.100000001490116, },
				PerspFarClip = Input { Value = 10000, },
				AovType = Input { Value = 1, },
				AoV = Input { Value = 27.6147445497038, },
				FLength = Input {
					SourceOp = "Camera1FocalLengthmm",
					Source = "Value",
				},
				["Stereo.Mode"] = Input { Value = FuID { "OffAxis" }, },
				FilmGate = Input { Value = FuID { "User" }, },
				ApertureW = Input { Value = 0.967559039592743, },
				ApertureH = Input { Value = 0.73511815071106, },
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 2, },
				["MtlStdInputs.MaterialID"] = Input { Value = 2, },
			},
			ViewInfo = OperatorInfo { Pos = { 134.264, -104.108 } },
		},
		Camera1XRotation = BezierSpline {
			SplineColor = { Red = 255, Green = 128, Blue = 128 },
			NameSet = true,
			KeyFrames = {
				[1] = { 0, Flags = { Linear = true } }
			}
		},
		Shape3D1 = Shape3D {
			Inputs = {
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 3, },
				["Transform3DOp.Scale.X"] = Input { Value = 200, },
				Shape = Input { Value = FuID { "SurfaceSphereInputs" }, },
				MaterialInput = Input {
					SourceOp = "Loader1_1",
					Source = "Output",
				},
				["MtlStdInputs.MaterialID"] = Input { Value = 3, },
				["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 128, },
				["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 128, },
				["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 4, }
			},
			ViewInfo = OperatorInfo { Pos = { 275, 82.5 } },
		},
		Transform3D1 = Transform3D {
			CtrlWZoom = false,
			Inputs = {
				SceneInput = Input {
					SourceOp = "Camera1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 244.264, -105.686 } },
		}
	},
	Frames = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			Left = 0,
			Top = 27,
			Width = 2560,
			Height = 1268,
			ZoneInfo = {
				["!Right"] = {
				},
				["!Left"] = {
				},
				AuxLeft = { Expanded = true },
				Right = { Expanded = true, },
				Left = { Expanded = false, },
				AuxRight = { Expanded = true }
			},
			ViewInfo = {
				Viewer1 = { Show = true, RatioX = 0.498595505617978, RatioY = 1, MRU = 4, Adjust = false, },
				InnerLeft = {
				},
				MainSplit = {
					RatioX = 1,
					RatioY = 0.342298288508557,
				},
				CenterSplit = {
					RatioX = 0.835745013687916,
					RatioY = 1,
				},
				Viewer2 = { Show = true, RatioX = 0.501404494382023, RatioY = 1, MRU = 1, Adjust = false, },
				Comments = { Show = false },
				Time = { Show = true, PixelY = 83, RatioX = 1, },
				InnerColumns = {
					RatioX = 1,
					RatioY = 0.616951915240424,
				},
				Keyframes = { Show = false, },
				LayoutStrip = { Show = true, RatioX = 1, },
				Inspector = { Show = true, RatioY = 1, RatioX = 1, },
				InnerRight = {
				},
				ActionStrip = { Show = true, RatioX = 1, },
				OuterColumns = {
					RatioX = 1,
					RatioY = 0.971541501976285,
				},
				Effects = { Show = false, },
				Clips = { Show = false, },
				Metadata = { Show = false, },
				OuterLeft = {
				},
				ViewerSplit = {
					RatioX = 1,
					RatioY = 0.89021164021164,
				},
				Nodes = { Show = true, RatioY = 1, RatioX = 1, },
				OuterRight = {
					RatioY = 1,
					PixelX = 420,
				},
				MediaPool = { Show = false, },
				Spline = { Show = false, }
			},
			Views = ordered() {
				Effects = MultiView {
					Active = "EffectView",
					ViewList = ordered() {
						EffectView = "EffectView"
					},
				},
				Nodes = MultiView {
					Active = "FlowView",
					ViewList = ordered() {
						FlowView = "FlowView"
					},
					Names = {
						FlowView = "FlowView"
					},
					FlowView = FlowView {
						Flags = {
							Navigator = true,
							AutoHideNavigator = true,
							AutoSnap = true,
							RemoveRouters = true
						},
						NavigatorSize = { 200, 140 },
						Direction = "Horizontal",
						PipeStyle = "Direct",
						Scale = 1.5,
						Offset = { 0, 0 }
					}
				},
				Keyframes = MultiView {
					Active = "TimelineView",
					ViewList = ordered() {
						TimelineView = "TimelineView"
					},
					Names = {
						TimelineView = "TimelineView"
					},
					TimelineView = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 232, Bottom = 320 },
							ScaleX = 0.385964912280702,
							OffsetX = -8.87719298245614,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = false,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "frame"
						},
						Spreadsheet = { LeftPos = 232, Visible = false }
					}
				},
				Spline = MultiView {
					Active = "SplineView",
					ViewList = ordered() {
						SplineView = "SplineEditorView"
					},
					Names = {
						SplineView = "SplineView"
					},
					SplineView = SplineEditorView {
						LeftPos = 264,
						ScaleX = 0.2,
						ScaleY = 0.00338983050847458,
						OffsetX = -3.4,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = false,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All"
					}
				},
				Inspector = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView"
					},
				},
				Viewer1 = MultiView {
					Active = "LeftView",
					ViewList = ordered() {
						LeftView = "PreviewContainer"
					},
					Names = {
						LeftView = "LeftView"
					},
				},
				Viewer2 = MultiView {
					Active = "RightView",
					ViewList = ordered() {
						RightView = "PreviewContainer"
					},
					Names = {
						RightView = "RightView"
					},
				},
				Time = "TimeView",
				ActionStrip = "ActionStripView",
				LayoutStrip = "LayoutStripView"
			},
			Layout = {
				Rows = 2,
				RatioX = 1,
				RatioY = 1,
				{ ID = "LayoutStrip", RatioX = 1, FixedY = 36, Flat = true },
				{
					Columns = 2,
					RatioY = 0.971541501976285,
					{
						Rows = 3,
						RatioX = 0.835745013687916,
						RatioY = 1,
						{
							Rows = 2,
							RatioX = 1,
							RatioY = 1,
							{
								Columns = 2,
								RatioX = 1,
								RatioY = 0.89021164021164,
								{ ID = "Viewer1", RatioX = 0.498595505617978, RatioY = 1 },
								{ ID = "Viewer2", RatioX = 0.501404494382023 }
							},
							{ ID = "Time", FixedY = 83, Flat = true }
						},
						{ ID = "ActionStrip", FixedY = 50, Flat = true },
						{ ID = "Nodes", RatioX = 1, RatioY = 1 }
					},
					{ ID = "Inspector", RatioX = 1, RatioY = 1 }
				}
			}
		}
	},
	Prefs = {
		Comp = {
			Views = {
				Right = {
					Viewer = {
						ScaleMode = 1
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							FitMarginY = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							NearZ = 0
						}
					},
					ViewLUT = {
						{
							Tools = ordered() {
								FusionViewLUT = ViewLUTOp {
									NameSet = true,
									Inputs = {
									}
								}
							},
							ID = "FusionViewLUT"
						},
						SelectedPlugin = "FusionViewLUT",
						SelectedName = ""
					}
				},
				Left = {
					Viewer = {
						EnableLUTs = true,
						Channel = 4294967295,
						Normalise = false,
						ScaleMode = 1,
						LUTSelected = "Fusion View LUT"
					},
					MaterialViewer = {
						Camera = {
							Rotation = {
								Y = -20,
								X = 15,
								Z = 0
							}
						}
					},
					SubView = {
						Enabled = true,
						Navigator = false,
						Magnifier = false,
						ID = "GLColorInspector",
						GLColorInspector = {
							AutoBounds = true
						}
					},
					ViewLUT = {
						{
							Tools = ordered() {
								FusionViewLUT = ViewLUTOp {
									NameSet = true,
									Inputs = {
									}
								}
							},
							ID = "FusionViewLUT"
						},
						Recent = {
							SelectedPlugin = "FusionViewLUT",
							FusionViewLUT = {
								Tools = ordered() {
									FusionViewLUT1 = ViewLUTOp {
										NameSet = true,
										Inputs = {
										}
									}
								}
							},
							SelectedName = "Fusion View LUT",
							GamutViewLUT = {
								Tools = ordered() {
									GamutViewLUT = ViewOperator {
										NameSet = true
									}
								}
							}
						},
						SelectedName = "Fusion View LUT",
						SelectedPlugin = "FusionViewLUT"
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							FitMarginY = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							NearZ = 0
						}
					}
				},
				View1 = {
					PrevCtrlInactiveColor = 0,
					PickW = 0,
					PickH = 0,
					PrevCtrlActiveColor = 0,
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							FitMarginY = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							NearZ = 0
						}
					}
				},
				RightView = {
					PickH = 1,
					PrevCtrlInactiveColor = 4278255360,
					PickW = 1,
					ViewLUT = {
						{
							Tools = ordered() {
								GamutViewLUT1 = ViewOperator {
									NameSet = true,
									Inputs = {
										OutputSpace = Input { Value = FuID { "sRGB" } }
									},
									CtrlWZoom = false
								}
							},
							ID = "GamutViewLUT"
						},
						Recent = {
							SelectedPlugin = "GamutViewLUT",
							FusionViewLUT = {
								Tools = ordered() {
									FusionViewLUT = ViewLUTOp {
										NameSet = true,
										Inputs = {
										}
									}
								}
							},
							OCIOColorSpaceViewLUT = {
								Tools = ordered() {
									OCIOColorSpaceViewLUT1 = ViewOperator {
										NameSet = true,
										Inputs = {
											OutputSpace = Input { Value = FuID { "raw" } },
											Look = Input { Value = FuID { "None" } },
											SourceSpace = Input { Value = FuID { "raw" } }
										}
									}
								}
							},
							GamutViewLUT = {
								Tools = ordered() {
									GamutViewLUT1 = ViewOperator {
										NameSet = true
									}
								}
							},
							SelectedName = "Gamut View LUT"
						},
						SelectedName = "Gamut View LUT",
						SelectedPlugin = "GamutViewLUT"
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							FitMarginY = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							NearZ = 0
						}
					},
					PrevCtrlActiveColor = 4278190335,
					Viewer = {
						EnableLUTs = true,
						LUTSelected = "Gamut View LUT",
						ScaleMode = 1,
						FitMarginY = 0,
						LUTPlugin = "GamutViewLUT",
						Channel = 4294967295,
						FitMarginX = 0,
						FitMarginType = 0,
						FarZ = -1000,
						NearZ = 0
					},
					View3D = {
						CamFront = {
							Rotation = {
								Y = 0,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamLeft = {
							Rotation = {
								Y = 90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamPersp = {
							Rotation = {
								Y = 0,
								X = 30,
								Z = 0
							},
							Scale = 0.131670132279396,
							Position = {
								Y = -0.0324846059083939,
								X = 0.245199352502823,
								Z = 0.0187549963593483
							}
						},
						CamTop = {
							Rotation = {
								Y = 0,
								X = 90,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamRight = {
							Rotation = {
								Y = -90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						}
					},
				},
				LeftView = {
					MaterialViewer = {
						Camera = {
							Rotation = {
								Y = -20,
								X = 15,
								Z = 0
							}
						}
					},
					PrevCtrlInactiveColor = 4278255360,
					PickW = 1,
					ViewLUT = {
						{
							Tools = ordered() {
								GamutViewLUT = ViewOperator {
									CtrlWZoom = false,
									NameSet = true,
									Inputs = {
										OutputSpace = Input { Value = FuID { "sRGB" }, },
									},
								}
							},
							ID = "GamutViewLUT"
						},
						Recent = {
							SelectedPlugin = "GamutViewLUT",
							FusionViewLUT = {
								Tools = ordered() {
									FusionViewLUT = ViewLUTOp {
										NameSet = true,
										Inputs = {
										}
									}
								}
							},
							SelectedName = "Gamut View LUT"
						},
						SelectedName = "Gamut View LUT",
						SelectedPlugin = "GamutViewLUT"
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							FitMarginY = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							NearZ = 0
						}
					},
					Viewer = {
						EnableLUTs = true,
						LUTSelected = "Gamut View LUT",
						ScaleMode = 1,
						FitMarginX = 0,
						LUTPlugin = "GamutViewLUT",
						Channel = 4294967295,
						NearZ = 0,
						FitMarginType = 0,
						FarZ = -1000,
						FitMarginY = 0,
					},
					SubView = {
						Enabled = false,
						Navigator = false,
						Magnifier = false,
						ID = "GLColorInspector",
						GLColorInspector = {
							AutoBounds = true
						}
					},
					PickH = 1,
					PrevCtrlActiveColor = 4278190335,
					View3D = {
						CamFront = {
							Rotation = {
								Y = 0,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamLeft = {
							Rotation = {
								Y = 90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamPersp = {
							Rotation = {
								Y = 0,
								X = 30,
								Z = 0
							},
							Scale = 0.18111777305603,
							Position = {
								Y = 0.0179078858345747,
								X = 0.0124069480225444,
								Z = -0.0103391231968999
							}
						},
						CamRight = {
							Rotation = {
								Y = -90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamTop = {
							Rotation = {
								Y = 0,
								X = 90,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						}
					},
				}
			},
			FrameFormat = {
				GuideRatio = 1.77777777777778,
				DepthFull = 3,
				DepthPreview = 3,
				DepthInteractive = 3,
			},
			LastFile = "/Volumes/Share/compdemo/enVRelight_Fusion/liquid.exr",
			Unsorted = {
				GlobalEnd = 180
			},
			Tweaks = {
				GPU = {
					Enable = 1,
				},
				OpenCL = {
					Enable = 1
				}
			},
			Paths = {
				EnableReverseMapping = true,
				Map = {
				}
			},
			QuickTime = {
			},
		}
	},
}

 